FROM postgres:18.4-alpine
LABEL MAINTAINER="ryota.kashio"

ENV TZ=Asia/Tokyo

RUN apk add --no-cache tzdata \
    && cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime \
    && echo "Asia/Tokyo" > /etc/timezone

EXPOSE 5432
