/** @type {import('tailwindcss').Config} */
export default {
  // HTMLとJSファイルをスキャン対象にする
  content: [
    "../static/js/**/*.js",
    "../templates/**/*.html",
    "../internal/**/*.go",
  ],
  theme: {
    extend: {},
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        solvi: {
          "color-scheme": "light",
          primary: "#1A4F86",
          secondary: "#2BB8B0",
          accent: "#F4C430",
          neutral: "#0E3A66",
          "base-100": "#ffffff",
          "base-200": "#f3f6f9",
          "base-300": "#dce6ef",
          "base-content": "#16324d",
          info: "#3abff8",
          success: "#36d399",
          warning: "#fbbd23",
          error: "#f87272",
        },
      },
      {
        wine: {
          "color-scheme": "light",
          primary: "#881337",
          secondary: "#9f1239",
          accent: "#be123c",
          neutral: "#4c0519",
          "base-100": "#ffffff",
          "base-200": "#f8f4f5",
          "base-300": "#eadfe2",
          "base-content": "#1f1316",
          info: "#3abff8",
          success: "#36d399",
          warning: "#fbbd23",
          error: "#f87272",
        },
      },
      "light",
      "dark",
      "cupcake",
      "coffee",
      "emerald",
      "corporate",
      "business",
      "winter",
      "nord",
      "aqua",
      "luxury",
      "dim",
      "night",
      "lofi",
    ],
  },
}
