// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/interface/repository/tag_repository.go
//
// Generated by this command:
//
//	mockgen -typed -source=internal/domain/interface/repository/tag_repository.go -destination=internal/domain/interface/repository/mock/mock_tag_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	repository "solvi/internal/domain/interface/repository"

	gomock "go.uber.org/mock/gomock"
)

// MockTagRepository is a mock of TagRepository interface.
type MockTagRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTagRepositoryMockRecorder
	isgomock struct{}
}

// MockTagRepositoryMockRecorder is the mock recorder for MockTagRepository.
type MockTagRepositoryMockRecorder struct {
	mock *MockTagRepository
}

// NewMockTagRepository creates a new mock instance.
func NewMockTagRepository(ctrl *gomock.Controller) *MockTagRepository {
	mock := &MockTagRepository{ctrl: ctrl}
	mock.recorder = &MockTagRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagRepository) EXPECT() *MockTagRepositoryMockRecorder {
	return m.recorder
}

// DeleteTagByName mocks base method.
func (m *MockTagRepository) DeleteTagByName(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTagByName", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTagByName indicates an expected call of DeleteTagByName.
func (mr *MockTagRepositoryMockRecorder) DeleteTagByName(ctx, name any) *MockTagRepositoryDeleteTagByNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTagByName", reflect.TypeOf((*MockTagRepository)(nil).DeleteTagByName), ctx, name)
	return &MockTagRepositoryDeleteTagByNameCall{Call: call}
}

// MockTagRepositoryDeleteTagByNameCall wrap *gomock.Call
type MockTagRepositoryDeleteTagByNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTagRepositoryDeleteTagByNameCall) Return(arg0 error) *MockTagRepositoryDeleteTagByNameCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTagRepositoryDeleteTagByNameCall) Do(f func(context.Context, string) error) *MockTagRepositoryDeleteTagByNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTagRepositoryDeleteTagByNameCall) DoAndReturn(f func(context.Context, string) error) *MockTagRepositoryDeleteTagByNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListTagStats mocks base method.
func (m *MockTagRepository) ListTagStats(ctx context.Context) ([]repository.TagStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTagStats", ctx)
	ret0, _ := ret[0].([]repository.TagStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTagStats indicates an expected call of ListTagStats.
func (mr *MockTagRepositoryMockRecorder) ListTagStats(ctx any) *MockTagRepositoryListTagStatsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTagStats", reflect.TypeOf((*MockTagRepository)(nil).ListTagStats), ctx)
	return &MockTagRepositoryListTagStatsCall{Call: call}
}

// MockTagRepositoryListTagStatsCall wrap *gomock.Call
type MockTagRepositoryListTagStatsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTagRepositoryListTagStatsCall) Return(arg0 []repository.TagStat, arg1 error) *MockTagRepositoryListTagStatsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTagRepositoryListTagStatsCall) Do(f func(context.Context) ([]repository.TagStat, error)) *MockTagRepositoryListTagStatsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTagRepositoryListTagStatsCall) DoAndReturn(f func(context.Context) ([]repository.TagStat, error)) *MockTagRepositoryListTagStatsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RenameTag mocks base method.
func (m *MockTagRepository) RenameTag(ctx context.Context, from, to string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenameTag", ctx, from, to)
	ret0, _ := ret[0].(error)
	return ret0
}

// RenameTag indicates an expected call of RenameTag.
func (mr *MockTagRepositoryMockRecorder) RenameTag(ctx, from, to any) *MockTagRepositoryRenameTagCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenameTag", reflect.TypeOf((*MockTagRepository)(nil).RenameTag), ctx, from, to)
	return &MockTagRepositoryRenameTagCall{Call: call}
}

// MockTagRepositoryRenameTagCall wrap *gomock.Call
type MockTagRepositoryRenameTagCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTagRepositoryRenameTagCall) Return(arg0 error) *MockTagRepositoryRenameTagCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTagRepositoryRenameTagCall) Do(f func(context.Context, string, string) error) *MockTagRepositoryRenameTagCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTagRepositoryRenameTagCall) DoAndReturn(f func(context.Context, string, string) error) *MockTagRepositoryRenameTagCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
