// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/interface/repository/question_repository.go
//
// Generated by this command:
//
//	mockgen -typed -source=internal/domain/interface/repository/question_repository.go -destination=internal/domain/interface/repository/mock/mock_question_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	entity "solvi/internal/domain/entity"

	gomock "go.uber.org/mock/gomock"
)

// MockQuestionRepository is a mock of QuestionRepository interface.
type MockQuestionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQuestionRepositoryMockRecorder
	isgomock struct{}
}

// MockQuestionRepositoryMockRecorder is the mock recorder for MockQuestionRepository.
type MockQuestionRepositoryMockRecorder struct {
	mock *MockQuestionRepository
}

// NewMockQuestionRepository creates a new mock instance.
func NewMockQuestionRepository(ctrl *gomock.Controller) *MockQuestionRepository {
	mock := &MockQuestionRepository{ctrl: ctrl}
	mock.recorder = &MockQuestionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuestionRepository) EXPECT() *MockQuestionRepositoryMockRecorder {
	return m.recorder
}

// AddAnswer mocks base method.
func (m *MockQuestionRepository) AddAnswer(answer *entity.QuestionAnswer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAnswer", answer)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAnswer indicates an expected call of AddAnswer.
func (mr *MockQuestionRepositoryMockRecorder) AddAnswer(answer any) *MockQuestionRepositoryAddAnswerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAnswer", reflect.TypeOf((*MockQuestionRepository)(nil).AddAnswer), answer)
	return &MockQuestionRepositoryAddAnswerCall{Call: call}
}

// MockQuestionRepositoryAddAnswerCall wrap *gomock.Call
type MockQuestionRepositoryAddAnswerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositoryAddAnswerCall) Return(arg0 error) *MockQuestionRepositoryAddAnswerCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositoryAddAnswerCall) Do(f func(*entity.QuestionAnswer) error) *MockQuestionRepositoryAddAnswerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositoryAddAnswerCall) DoAndReturn(f func(*entity.QuestionAnswer) error) *MockQuestionRepositoryAddAnswerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddContent mocks base method.
func (m *MockQuestionRepository) AddContent(content *entity.QuestionContent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddContent", content)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddContent indicates an expected call of AddContent.
func (mr *MockQuestionRepositoryMockRecorder) AddContent(content any) *MockQuestionRepositoryAddContentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddContent", reflect.TypeOf((*MockQuestionRepository)(nil).AddContent), content)
	return &MockQuestionRepositoryAddContentCall{Call: call}
}

// MockQuestionRepositoryAddContentCall wrap *gomock.Call
type MockQuestionRepositoryAddContentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositoryAddContentCall) Return(arg0 error) *MockQuestionRepositoryAddContentCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositoryAddContentCall) Do(f func(*entity.QuestionContent) error) *MockQuestionRepositoryAddContentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositoryAddContentCall) DoAndReturn(f func(*entity.QuestionContent) error) *MockQuestionRepositoryAddContentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddMemo mocks base method.
func (m *MockQuestionRepository) AddMemo(memo *entity.QuestionMemo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMemo", memo)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMemo indicates an expected call of AddMemo.
func (mr *MockQuestionRepositoryMockRecorder) AddMemo(memo any) *MockQuestionRepositoryAddMemoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMemo", reflect.TypeOf((*MockQuestionRepository)(nil).AddMemo), memo)
	return &MockQuestionRepositoryAddMemoCall{Call: call}
}

// MockQuestionRepositoryAddMemoCall wrap *gomock.Call
type MockQuestionRepositoryAddMemoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositoryAddMemoCall) Return(arg0 error) *MockQuestionRepositoryAddMemoCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositoryAddMemoCall) Do(f func(*entity.QuestionMemo) error) *MockQuestionRepositoryAddMemoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositoryAddMemoCall) DoAndReturn(f func(*entity.QuestionMemo) error) *MockQuestionRepositoryAddMemoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SoftDeleteAnswerByUUID mocks base method.
func (m *MockQuestionRepository) SoftDeleteAnswerByUUID(uuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteAnswerByUUID", uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteAnswerByUUID indicates an expected call of SoftDeleteAnswerByUUID.
func (mr *MockQuestionRepositoryMockRecorder) SoftDeleteAnswerByUUID(uuid any) *MockQuestionRepositorySoftDeleteAnswerByUUIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteAnswerByUUID", reflect.TypeOf((*MockQuestionRepository)(nil).SoftDeleteAnswerByUUID), uuid)
	return &MockQuestionRepositorySoftDeleteAnswerByUUIDCall{Call: call}
}

// MockQuestionRepositorySoftDeleteAnswerByUUIDCall wrap *gomock.Call
type MockQuestionRepositorySoftDeleteAnswerByUUIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositorySoftDeleteAnswerByUUIDCall) Return(arg0 error) *MockQuestionRepositorySoftDeleteAnswerByUUIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositorySoftDeleteAnswerByUUIDCall) Do(f func(string) error) *MockQuestionRepositorySoftDeleteAnswerByUUIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositorySoftDeleteAnswerByUUIDCall) DoAndReturn(f func(string) error) *MockQuestionRepositorySoftDeleteAnswerByUUIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SoftDeleteByUUID mocks base method.
func (m *MockQuestionRepository) SoftDeleteByUUID(uuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteByUUID", uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteByUUID indicates an expected call of SoftDeleteByUUID.
func (mr *MockQuestionRepositoryMockRecorder) SoftDeleteByUUID(uuid any) *MockQuestionRepositorySoftDeleteByUUIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteByUUID", reflect.TypeOf((*MockQuestionRepository)(nil).SoftDeleteByUUID), uuid)
	return &MockQuestionRepositorySoftDeleteByUUIDCall{Call: call}
}

// MockQuestionRepositorySoftDeleteByUUIDCall wrap *gomock.Call
type MockQuestionRepositorySoftDeleteByUUIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositorySoftDeleteByUUIDCall) Return(arg0 error) *MockQuestionRepositorySoftDeleteByUUIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositorySoftDeleteByUUIDCall) Do(f func(string) error) *MockQuestionRepositorySoftDeleteByUUIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositorySoftDeleteByUUIDCall) DoAndReturn(f func(string) error) *MockQuestionRepositorySoftDeleteByUUIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SoftDeleteMemoByUUID mocks base method.
func (m *MockQuestionRepository) SoftDeleteMemoByUUID(uuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteMemoByUUID", uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteMemoByUUID indicates an expected call of SoftDeleteMemoByUUID.
func (mr *MockQuestionRepositoryMockRecorder) SoftDeleteMemoByUUID(uuid any) *MockQuestionRepositorySoftDeleteMemoByUUIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteMemoByUUID", reflect.TypeOf((*MockQuestionRepository)(nil).SoftDeleteMemoByUUID), uuid)
	return &MockQuestionRepositorySoftDeleteMemoByUUIDCall{Call: call}
}

// MockQuestionRepositorySoftDeleteMemoByUUIDCall wrap *gomock.Call
type MockQuestionRepositorySoftDeleteMemoByUUIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositorySoftDeleteMemoByUUIDCall) Return(arg0 error) *MockQuestionRepositorySoftDeleteMemoByUUIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositorySoftDeleteMemoByUUIDCall) Do(f func(string) error) *MockQuestionRepositorySoftDeleteMemoByUUIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositorySoftDeleteMemoByUUIDCall) DoAndReturn(f func(string) error) *MockQuestionRepositorySoftDeleteMemoByUUIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddRefer mocks base method.
func (m *MockQuestionRepository) AddRefer(refer *entity.QuestionRefer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRefer", refer)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRefer indicates an expected call of AddRefer.
func (mr *MockQuestionRepositoryMockRecorder) AddRefer(refer any) *MockQuestionRepositoryAddReferCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRefer", reflect.TypeOf((*MockQuestionRepository)(nil).AddRefer), refer)
	return &MockQuestionRepositoryAddReferCall{Call: call}
}

// MockQuestionRepositoryAddReferCall wrap *gomock.Call
type MockQuestionRepositoryAddReferCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositoryAddReferCall) Return(arg0 error) *MockQuestionRepositoryAddReferCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositoryAddReferCall) Do(f func(*entity.QuestionRefer) error) *MockQuestionRepositoryAddReferCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositoryAddReferCall) DoAndReturn(f func(*entity.QuestionRefer) error) *MockQuestionRepositoryAddReferCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Create mocks base method.
func (m *MockQuestionRepository) Create(question *entity.Question) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", question)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockQuestionRepositoryMockRecorder) Create(question any) *MockQuestionRepositoryCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockQuestionRepository)(nil).Create), question)
	return &MockQuestionRepositoryCreateCall{Call: call}
}

// MockQuestionRepositoryCreateCall wrap *gomock.Call
type MockQuestionRepositoryCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositoryCreateCall) Return(arg0 error) *MockQuestionRepositoryCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositoryCreateCall) Do(f func(*entity.Question) error) *MockQuestionRepositoryCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositoryCreateCall) DoAndReturn(f func(*entity.Question) error) *MockQuestionRepositoryCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateSummary mocks base method.
func (m *MockQuestionRepository) CreateSummary(summary *entity.QuestionSummary, refs []entity.QuestionSummaryReference) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSummary", summary, refs)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSummary indicates an expected call of CreateSummary.
func (mr *MockQuestionRepositoryMockRecorder) CreateSummary(summary, refs any) *MockQuestionRepositoryCreateSummaryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSummary", reflect.TypeOf((*MockQuestionRepository)(nil).CreateSummary), summary, refs)
	return &MockQuestionRepositoryCreateSummaryCall{Call: call}
}

// MockQuestionRepositoryCreateSummaryCall wrap *gomock.Call
type MockQuestionRepositoryCreateSummaryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositoryCreateSummaryCall) Return(arg0 error) *MockQuestionRepositoryCreateSummaryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositoryCreateSummaryCall) Do(f func(*entity.QuestionSummary, []entity.QuestionSummaryReference) error) *MockQuestionRepositoryCreateSummaryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositoryCreateSummaryCall) DoAndReturn(f func(*entity.QuestionSummary, []entity.QuestionSummaryReference) error) *MockQuestionRepositoryCreateSummaryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByUUID mocks base method.
func (m *MockQuestionRepository) GetByUUID(uuid string) (*entity.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUUID", uuid)
	ret0, _ := ret[0].(*entity.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUUID indicates an expected call of GetByUUID.
func (mr *MockQuestionRepositoryMockRecorder) GetByUUID(uuid any) *MockQuestionRepositoryGetByUUIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUUID", reflect.TypeOf((*MockQuestionRepository)(nil).GetByUUID), uuid)
	return &MockQuestionRepositoryGetByUUIDCall{Call: call}
}

// MockQuestionRepositoryGetByUUIDCall wrap *gomock.Call
type MockQuestionRepositoryGetByUUIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositoryGetByUUIDCall) Return(arg0 *entity.Question, arg1 error) *MockQuestionRepositoryGetByUUIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositoryGetByUUIDCall) Do(f func(string) (*entity.Question, error)) *MockQuestionRepositoryGetByUUIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositoryGetByUUIDCall) DoAndReturn(f func(string) (*entity.Question, error)) *MockQuestionRepositoryGetByUUIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListAll mocks base method.
func (m *MockQuestionRepository) ListAll() ([]entity.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll")
	ret0, _ := ret[0].([]entity.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockQuestionRepositoryMockRecorder) ListAll() *MockQuestionRepositoryListAllCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockQuestionRepository)(nil).ListAll))
	return &MockQuestionRepositoryListAllCall{Call: call}
}

// MockQuestionRepositoryListAllCall wrap *gomock.Call
type MockQuestionRepositoryListAllCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositoryListAllCall) Return(arg0 []entity.Question, arg1 error) *MockQuestionRepositoryListAllCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositoryListAllCall) Do(f func() ([]entity.Question, error)) *MockQuestionRepositoryListAllCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositoryListAllCall) DoAndReturn(f func() ([]entity.Question, error)) *MockQuestionRepositoryListAllCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListByQuestionUserID mocks base method.
func (m *MockQuestionRepository) ListByQuestionUserID(userID uint) ([]entity.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByQuestionUserID", userID)
	ret0, _ := ret[0].([]entity.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByQuestionUserID indicates an expected call of ListByQuestionUserID.
func (mr *MockQuestionRepositoryMockRecorder) ListByQuestionUserID(userID any) *MockQuestionRepositoryListByQuestionUserIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByQuestionUserID", reflect.TypeOf((*MockQuestionRepository)(nil).ListByQuestionUserID), userID)
	return &MockQuestionRepositoryListByQuestionUserIDCall{Call: call}
}

// MockQuestionRepositoryListByQuestionUserIDCall wrap *gomock.Call
type MockQuestionRepositoryListByQuestionUserIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositoryListByQuestionUserIDCall) Return(arg0 []entity.Question, arg1 error) *MockQuestionRepositoryListByQuestionUserIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositoryListByQuestionUserIDCall) Do(f func(uint) ([]entity.Question, error)) *MockQuestionRepositoryListByQuestionUserIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositoryListByQuestionUserIDCall) DoAndReturn(f func(uint) ([]entity.Question, error)) *MockQuestionRepositoryListByQuestionUserIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReplaceTags mocks base method.
func (m *MockQuestionRepository) ReplaceTags(questionID uint, tags []entity.QuestionTag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceTags", questionID, tags)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceTags indicates an expected call of ReplaceTags.
func (mr *MockQuestionRepositoryMockRecorder) ReplaceTags(questionID, tags any) *MockQuestionRepositoryReplaceTagsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceTags", reflect.TypeOf((*MockQuestionRepository)(nil).ReplaceTags), questionID, tags)
	return &MockQuestionRepositoryReplaceTagsCall{Call: call}
}

// MockQuestionRepositoryReplaceTagsCall wrap *gomock.Call
type MockQuestionRepositoryReplaceTagsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositoryReplaceTagsCall) Return(arg0 error) *MockQuestionRepositoryReplaceTagsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositoryReplaceTagsCall) Do(f func(uint, []entity.QuestionTag) error) *MockQuestionRepositoryReplaceTagsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositoryReplaceTagsCall) DoAndReturn(f func(uint, []entity.QuestionTag) error) *MockQuestionRepositoryReplaceTagsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockQuestionRepository) Update(question *entity.Question) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", question)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockQuestionRepositoryMockRecorder) Update(question any) *MockQuestionRepositoryUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockQuestionRepository)(nil).Update), question)
	return &MockQuestionRepositoryUpdateCall{Call: call}
}

// MockQuestionRepositoryUpdateCall wrap *gomock.Call
type MockQuestionRepositoryUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositoryUpdateCall) Return(arg0 error) *MockQuestionRepositoryUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositoryUpdateCall) Do(f func(*entity.Question) error) *MockQuestionRepositoryUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositoryUpdateCall) DoAndReturn(f func(*entity.Question) error) *MockQuestionRepositoryUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
