// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/interface/repository/question_repository.go
//
// Generated by this command:
//
//	mockgen -typed -source=internal/domain/interface/repository/question_repository.go -destination=internal/domain/interface/repository/mock/mock_question_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	entity "solvi/internal/domain/entity"

	gomock "go.uber.org/mock/gomock"
)

// MockQuestionRepository is a mock of QuestionRepository interface.
type MockQuestionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQuestionRepositoryMockRecorder
	isgomock struct{}
}

// MockQuestionRepositoryMockRecorder is the mock recorder for MockQuestionRepository.
type MockQuestionRepositoryMockRecorder struct {
	mock *MockQuestionRepository
}

// NewMockQuestionRepository creates a new mock instance.
func NewMockQuestionRepository(ctrl *gomock.Controller) *MockQuestionRepository {
	mock := &MockQuestionRepository{ctrl: ctrl}
	mock.recorder = &MockQuestionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuestionRepository) EXPECT() *MockQuestionRepositoryMockRecorder {
	return m.recorder
}

// AddAnswer mocks base method.
func (m *MockQuestionRepository) AddAnswer(ctx context.Context, answer *entity.QuestionAnswer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAnswer", ctx, answer)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAnswer indicates an expected call of AddAnswer.
func (mr *MockQuestionRepositoryMockRecorder) AddAnswer(ctx, answer any) *MockQuestionRepositoryAddAnswerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAnswer", reflect.TypeOf((*MockQuestionRepository)(nil).AddAnswer), ctx, answer)
	return &MockQuestionRepositoryAddAnswerCall{Call: call}
}

// MockQuestionRepositoryAddAnswerCall wrap *gomock.Call
type MockQuestionRepositoryAddAnswerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositoryAddAnswerCall) Return(arg0 error) *MockQuestionRepositoryAddAnswerCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositoryAddAnswerCall) Do(f func(context.Context, *entity.QuestionAnswer) error) *MockQuestionRepositoryAddAnswerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositoryAddAnswerCall) DoAndReturn(f func(context.Context, *entity.QuestionAnswer) error) *MockQuestionRepositoryAddAnswerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddContent mocks base method.
func (m *MockQuestionRepository) AddContent(ctx context.Context, content *entity.QuestionContent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddContent", ctx, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddContent indicates an expected call of AddContent.
func (mr *MockQuestionRepositoryMockRecorder) AddContent(ctx, content any) *MockQuestionRepositoryAddContentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddContent", reflect.TypeOf((*MockQuestionRepository)(nil).AddContent), ctx, content)
	return &MockQuestionRepositoryAddContentCall{Call: call}
}

// MockQuestionRepositoryAddContentCall wrap *gomock.Call
type MockQuestionRepositoryAddContentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositoryAddContentCall) Return(arg0 error) *MockQuestionRepositoryAddContentCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositoryAddContentCall) Do(f func(context.Context, *entity.QuestionContent) error) *MockQuestionRepositoryAddContentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositoryAddContentCall) DoAndReturn(f func(context.Context, *entity.QuestionContent) error) *MockQuestionRepositoryAddContentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddMemo mocks base method.
func (m *MockQuestionRepository) AddMemo(ctx context.Context, memo *entity.QuestionMemo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMemo", ctx, memo)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMemo indicates an expected call of AddMemo.
func (mr *MockQuestionRepositoryMockRecorder) AddMemo(ctx, memo any) *MockQuestionRepositoryAddMemoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMemo", reflect.TypeOf((*MockQuestionRepository)(nil).AddMemo), ctx, memo)
	return &MockQuestionRepositoryAddMemoCall{Call: call}
}

// MockQuestionRepositoryAddMemoCall wrap *gomock.Call
type MockQuestionRepositoryAddMemoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositoryAddMemoCall) Return(arg0 error) *MockQuestionRepositoryAddMemoCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositoryAddMemoCall) Do(f func(context.Context, *entity.QuestionMemo) error) *MockQuestionRepositoryAddMemoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositoryAddMemoCall) DoAndReturn(f func(context.Context, *entity.QuestionMemo) error) *MockQuestionRepositoryAddMemoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddRefer mocks base method.
func (m *MockQuestionRepository) AddRefer(ctx context.Context, refer *entity.QuestionRefer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRefer", ctx, refer)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRefer indicates an expected call of AddRefer.
func (mr *MockQuestionRepositoryMockRecorder) AddRefer(ctx, refer any) *MockQuestionRepositoryAddReferCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRefer", reflect.TypeOf((*MockQuestionRepository)(nil).AddRefer), ctx, refer)
	return &MockQuestionRepositoryAddReferCall{Call: call}
}

// MockQuestionRepositoryAddReferCall wrap *gomock.Call
type MockQuestionRepositoryAddReferCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositoryAddReferCall) Return(arg0 error) *MockQuestionRepositoryAddReferCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositoryAddReferCall) Do(f func(context.Context, *entity.QuestionRefer) error) *MockQuestionRepositoryAddReferCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositoryAddReferCall) DoAndReturn(f func(context.Context, *entity.QuestionRefer) error) *MockQuestionRepositoryAddReferCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Create mocks base method.
func (m *MockQuestionRepository) Create(ctx context.Context, question *entity.Question) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, question)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockQuestionRepositoryMockRecorder) Create(ctx, question any) *MockQuestionRepositoryCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockQuestionRepository)(nil).Create), ctx, question)
	return &MockQuestionRepositoryCreateCall{Call: call}
}

// MockQuestionRepositoryCreateCall wrap *gomock.Call
type MockQuestionRepositoryCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositoryCreateCall) Return(arg0 error) *MockQuestionRepositoryCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositoryCreateCall) Do(f func(context.Context, *entity.Question) error) *MockQuestionRepositoryCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositoryCreateCall) DoAndReturn(f func(context.Context, *entity.Question) error) *MockQuestionRepositoryCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateSummary mocks base method.
func (m *MockQuestionRepository) CreateSummary(ctx context.Context, summary *entity.QuestionSummary, refs []entity.QuestionSummaryReference) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSummary", ctx, summary, refs)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSummary indicates an expected call of CreateSummary.
func (mr *MockQuestionRepositoryMockRecorder) CreateSummary(ctx, summary, refs any) *MockQuestionRepositoryCreateSummaryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSummary", reflect.TypeOf((*MockQuestionRepository)(nil).CreateSummary), ctx, summary, refs)
	return &MockQuestionRepositoryCreateSummaryCall{Call: call}
}

// MockQuestionRepositoryCreateSummaryCall wrap *gomock.Call
type MockQuestionRepositoryCreateSummaryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositoryCreateSummaryCall) Return(arg0 error) *MockQuestionRepositoryCreateSummaryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositoryCreateSummaryCall) Do(f func(context.Context, *entity.QuestionSummary, []entity.QuestionSummaryReference) error) *MockQuestionRepositoryCreateSummaryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositoryCreateSummaryCall) DoAndReturn(f func(context.Context, *entity.QuestionSummary, []entity.QuestionSummaryReference) error) *MockQuestionRepositoryCreateSummaryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByUUID mocks base method.
func (m *MockQuestionRepository) GetByUUID(ctx context.Context, uuid string) (*entity.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUUID", ctx, uuid)
	ret0, _ := ret[0].(*entity.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUUID indicates an expected call of GetByUUID.
func (mr *MockQuestionRepositoryMockRecorder) GetByUUID(ctx, uuid any) *MockQuestionRepositoryGetByUUIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUUID", reflect.TypeOf((*MockQuestionRepository)(nil).GetByUUID), ctx, uuid)
	return &MockQuestionRepositoryGetByUUIDCall{Call: call}
}

// MockQuestionRepositoryGetByUUIDCall wrap *gomock.Call
type MockQuestionRepositoryGetByUUIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositoryGetByUUIDCall) Return(arg0 *entity.Question, arg1 error) *MockQuestionRepositoryGetByUUIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositoryGetByUUIDCall) Do(f func(context.Context, string) (*entity.Question, error)) *MockQuestionRepositoryGetByUUIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositoryGetByUUIDCall) DoAndReturn(f func(context.Context, string) (*entity.Question, error)) *MockQuestionRepositoryGetByUUIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListAll mocks base method.
func (m *MockQuestionRepository) ListAll(ctx context.Context) ([]entity.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", ctx)
	ret0, _ := ret[0].([]entity.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockQuestionRepositoryMockRecorder) ListAll(ctx any) *MockQuestionRepositoryListAllCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockQuestionRepository)(nil).ListAll), ctx)
	return &MockQuestionRepositoryListAllCall{Call: call}
}

// MockQuestionRepositoryListAllCall wrap *gomock.Call
type MockQuestionRepositoryListAllCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositoryListAllCall) Return(arg0 []entity.Question, arg1 error) *MockQuestionRepositoryListAllCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositoryListAllCall) Do(f func(context.Context) ([]entity.Question, error)) *MockQuestionRepositoryListAllCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositoryListAllCall) DoAndReturn(f func(context.Context) ([]entity.Question, error)) *MockQuestionRepositoryListAllCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListByQuestionUserID mocks base method.
func (m *MockQuestionRepository) ListByQuestionUserID(ctx context.Context, userID uint) ([]entity.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByQuestionUserID", ctx, userID)
	ret0, _ := ret[0].([]entity.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByQuestionUserID indicates an expected call of ListByQuestionUserID.
func (mr *MockQuestionRepositoryMockRecorder) ListByQuestionUserID(ctx, userID any) *MockQuestionRepositoryListByQuestionUserIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByQuestionUserID", reflect.TypeOf((*MockQuestionRepository)(nil).ListByQuestionUserID), ctx, userID)
	return &MockQuestionRepositoryListByQuestionUserIDCall{Call: call}
}

// MockQuestionRepositoryListByQuestionUserIDCall wrap *gomock.Call
type MockQuestionRepositoryListByQuestionUserIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositoryListByQuestionUserIDCall) Return(arg0 []entity.Question, arg1 error) *MockQuestionRepositoryListByQuestionUserIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositoryListByQuestionUserIDCall) Do(f func(context.Context, uint) ([]entity.Question, error)) *MockQuestionRepositoryListByQuestionUserIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositoryListByQuestionUserIDCall) DoAndReturn(f func(context.Context, uint) ([]entity.Question, error)) *MockQuestionRepositoryListByQuestionUserIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReplaceTags mocks base method.
func (m *MockQuestionRepository) ReplaceTags(ctx context.Context, questionID uint, tags []entity.QuestionTag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceTags", ctx, questionID, tags)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceTags indicates an expected call of ReplaceTags.
func (mr *MockQuestionRepositoryMockRecorder) ReplaceTags(ctx, questionID, tags any) *MockQuestionRepositoryReplaceTagsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceTags", reflect.TypeOf((*MockQuestionRepository)(nil).ReplaceTags), ctx, questionID, tags)
	return &MockQuestionRepositoryReplaceTagsCall{Call: call}
}

// MockQuestionRepositoryReplaceTagsCall wrap *gomock.Call
type MockQuestionRepositoryReplaceTagsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositoryReplaceTagsCall) Return(arg0 error) *MockQuestionRepositoryReplaceTagsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositoryReplaceTagsCall) Do(f func(context.Context, uint, []entity.QuestionTag) error) *MockQuestionRepositoryReplaceTagsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositoryReplaceTagsCall) DoAndReturn(f func(context.Context, uint, []entity.QuestionTag) error) *MockQuestionRepositoryReplaceTagsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SoftDeleteAnswerByUUID mocks base method.
func (m *MockQuestionRepository) SoftDeleteAnswerByUUID(ctx context.Context, uuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteAnswerByUUID", ctx, uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteAnswerByUUID indicates an expected call of SoftDeleteAnswerByUUID.
func (mr *MockQuestionRepositoryMockRecorder) SoftDeleteAnswerByUUID(ctx, uuid any) *MockQuestionRepositorySoftDeleteAnswerByUUIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteAnswerByUUID", reflect.TypeOf((*MockQuestionRepository)(nil).SoftDeleteAnswerByUUID), ctx, uuid)
	return &MockQuestionRepositorySoftDeleteAnswerByUUIDCall{Call: call}
}

// MockQuestionRepositorySoftDeleteAnswerByUUIDCall wrap *gomock.Call
type MockQuestionRepositorySoftDeleteAnswerByUUIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositorySoftDeleteAnswerByUUIDCall) Return(arg0 error) *MockQuestionRepositorySoftDeleteAnswerByUUIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositorySoftDeleteAnswerByUUIDCall) Do(f func(context.Context, string) error) *MockQuestionRepositorySoftDeleteAnswerByUUIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositorySoftDeleteAnswerByUUIDCall) DoAndReturn(f func(context.Context, string) error) *MockQuestionRepositorySoftDeleteAnswerByUUIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SoftDeleteByUUID mocks base method.
func (m *MockQuestionRepository) SoftDeleteByUUID(ctx context.Context, uuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteByUUID", ctx, uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteByUUID indicates an expected call of SoftDeleteByUUID.
func (mr *MockQuestionRepositoryMockRecorder) SoftDeleteByUUID(ctx, uuid any) *MockQuestionRepositorySoftDeleteByUUIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteByUUID", reflect.TypeOf((*MockQuestionRepository)(nil).SoftDeleteByUUID), ctx, uuid)
	return &MockQuestionRepositorySoftDeleteByUUIDCall{Call: call}
}

// MockQuestionRepositorySoftDeleteByUUIDCall wrap *gomock.Call
type MockQuestionRepositorySoftDeleteByUUIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositorySoftDeleteByUUIDCall) Return(arg0 error) *MockQuestionRepositorySoftDeleteByUUIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositorySoftDeleteByUUIDCall) Do(f func(context.Context, string) error) *MockQuestionRepositorySoftDeleteByUUIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositorySoftDeleteByUUIDCall) DoAndReturn(f func(context.Context, string) error) *MockQuestionRepositorySoftDeleteByUUIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SoftDeleteMemoByUUID mocks base method.
func (m *MockQuestionRepository) SoftDeleteMemoByUUID(ctx context.Context, uuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteMemoByUUID", ctx, uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteMemoByUUID indicates an expected call of SoftDeleteMemoByUUID.
func (mr *MockQuestionRepositoryMockRecorder) SoftDeleteMemoByUUID(ctx, uuid any) *MockQuestionRepositorySoftDeleteMemoByUUIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteMemoByUUID", reflect.TypeOf((*MockQuestionRepository)(nil).SoftDeleteMemoByUUID), ctx, uuid)
	return &MockQuestionRepositorySoftDeleteMemoByUUIDCall{Call: call}
}

// MockQuestionRepositorySoftDeleteMemoByUUIDCall wrap *gomock.Call
type MockQuestionRepositorySoftDeleteMemoByUUIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositorySoftDeleteMemoByUUIDCall) Return(arg0 error) *MockQuestionRepositorySoftDeleteMemoByUUIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositorySoftDeleteMemoByUUIDCall) Do(f func(context.Context, string) error) *MockQuestionRepositorySoftDeleteMemoByUUIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositorySoftDeleteMemoByUUIDCall) DoAndReturn(f func(context.Context, string) error) *MockQuestionRepositorySoftDeleteMemoByUUIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SoftDeleteReferByUUID mocks base method.
func (m *MockQuestionRepository) SoftDeleteReferByUUID(ctx context.Context, uuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteReferByUUID", ctx, uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteReferByUUID indicates an expected call of SoftDeleteReferByUUID.
func (mr *MockQuestionRepositoryMockRecorder) SoftDeleteReferByUUID(ctx, uuid any) *MockQuestionRepositorySoftDeleteReferByUUIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteReferByUUID", reflect.TypeOf((*MockQuestionRepository)(nil).SoftDeleteReferByUUID), ctx, uuid)
	return &MockQuestionRepositorySoftDeleteReferByUUIDCall{Call: call}
}

// MockQuestionRepositorySoftDeleteReferByUUIDCall wrap *gomock.Call
type MockQuestionRepositorySoftDeleteReferByUUIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositorySoftDeleteReferByUUIDCall) Return(arg0 error) *MockQuestionRepositorySoftDeleteReferByUUIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositorySoftDeleteReferByUUIDCall) Do(f func(context.Context, string) error) *MockQuestionRepositorySoftDeleteReferByUUIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositorySoftDeleteReferByUUIDCall) DoAndReturn(f func(context.Context, string) error) *MockQuestionRepositorySoftDeleteReferByUUIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockQuestionRepository) Update(ctx context.Context, question *entity.Question) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, question)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockQuestionRepositoryMockRecorder) Update(ctx, question any) *MockQuestionRepositoryUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockQuestionRepository)(nil).Update), ctx, question)
	return &MockQuestionRepositoryUpdateCall{Call: call}
}

// MockQuestionRepositoryUpdateCall wrap *gomock.Call
type MockQuestionRepositoryUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQuestionRepositoryUpdateCall) Return(arg0 error) *MockQuestionRepositoryUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQuestionRepositoryUpdateCall) Do(f func(context.Context, *entity.Question) error) *MockQuestionRepositoryUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQuestionRepositoryUpdateCall) DoAndReturn(f func(context.Context, *entity.Question) error) *MockQuestionRepositoryUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
